# Generated by Django 3.0.5 on 2020-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=20)),
                ('cus_mob', models.CharField(max_length=20)),
                ('cus_time', models.CharField(max_length=20)),
                ('cus_country', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
    ]
